# Generated by Django 3.2.8 on 2021-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Second_Name', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=40)),
                ('Work_field', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Add_Time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
