# Generated by Django 3.2.8 on 2021-10-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_auto_20211030_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vectorwork',
            options={'ordering': ['name'], 'verbose_name': 'Область бизнеса', 'verbose_name_plural': 'Области бизнеса'},
        ),
        migrations.RenameField(
            model_name='vectorwork',
            old_name='bis',
            new_name='name',
        ),
    ]
